flags: {}
extra-include-dirs:
- /usr/local/include
extra-lib-dirs:
- /usr/local/lib
packages:
- ethereum-analyzer/
- ethereum-analyzer-cli/
- ethereum-analyzer-deps/
- ethereum-analyzer-webui/
extra-deps:
- global-lock-0.1
- logging-effect-1.1.1
resolver: lts-8.24
